import type { ElementType } from 'react';
import {
  MessageCircle,
  Phone,
  Mail,
  Users,
  Trophy,
  FileText,
  Globe,
  Gift,
  FlaskConical,
  Calendar,
  Sparkles,
  Flame,
  Swords,
  Shield,
  Zap,
  Star,
  Target,
  Crosshair,
  TrendingUp,
  Rocket,
  Crown,
  Tag,
  Eye,
  Send,
  Handshake,
  Gem,
  Award,
  Medal,
  Sword,
  Activity,
  Egg, Bird, Wand2, Sun,
  Package, Box,
  Cherry, Citrus,
  Home, Store, Wheat, Trees, Landmark, Building2, Castle, Mountain, Church, Hammer,
  Pencil, Repeat, Infinity as InfinityIcon, Feather, Moon, Compass, Flower2, Leaf, Anchor, Smile, Sunrise, AlertTriangle, CircleDashed, ArrowRight,
  Coins, Banknote, Diamond, PiggyBank,
  Warehouse, Factory, Tent, TreePine, Tractor, GraduationCap,
  Skull, Drama, KeyRound, Telescope, Library, Ship,
  GaugeCircle, BookOpen, Atom, Layers,
  Cat, Dog, Rabbit, Fish,
  Hexagon, Triangle, ChevronsUp, Cloud, Wind, Snowflake,
} from 'lucide-react';
import {
  IconSword,
  IconShield,
  IconSkull,
  IconFlame,
  IconSparkles,
  IconStar,
  IconTarget,
  IconTrophy,
  IconCrown,
  IconDiamond,
  IconGift,
  IconPackage,
  IconBox,
  IconLock,
  IconLockOpen,
  IconCalendar,
  IconBolt,
  IconTrendingUp,
  IconRocket,
  IconFlag,
  IconChecklist,
  IconHourglass,
  IconMap,
  IconBookmark,
  IconDice,
  IconCoins,
  IconMoon,
  IconSun,
  IconHeart,
  IconCrosshair,
  IconCompass,
  IconAnchor,
  IconFeather,
  IconLeaf,
  IconWind,
  IconCloud,
  IconSnowflake,
  IconHexagon,
  IconTriangle,
  IconAlertTriangle,
  IconArrowRight,
  IconPhone,
  IconMail,
  IconUsers,
  IconPencil,
  IconRepeat,
  IconSunrise,
  IconCashBanknote,
  IconPigMoney,
  IconTent,
  IconKey,
  IconTelescope,
  IconShip,
  IconGauge,
  IconBook,
  IconAtom,
  IconCat,
  IconDog,
  IconFish,
  IconEgg,
  IconTag,
  IconEye,
  IconSend,
  IconBuilding,
  IconHammer,
  IconChevronRight,
  IconCheck,
  IconChevronDown,
  IconChevronUp,
  IconHome,
  IconTree,
  IconMountain,
  IconMessageCircle,
  IconFileText,
  IconGlobe,
  IconWorld,
} from '@tabler/icons-react';
import type { Rareza, Categoria } from './types';

/* ============================================================
   Iconos + rarezas + categorias
============================================================ */

// Tipo generico que acepta iconos de Lucide, Tabler o cualquier biblioteca
export type IconType = ElementType<{ className?: string; strokeWidth?: string | number }>;

export const ICON_MAP: Record<string, IconType> = {
  // Lucide (originales)
  MessageCircle, Phone, Mail, Users, Trophy, FileText, Globe, Gift,
  FlaskConical, Calendar, Sparkles, Swords, Shield, Star, Zap,
  Target, Crosshair, TrendingUp, Rocket, Crown, Tag, Eye, Send,
  Handshake, Flame, Award, Medal,
  Egg, Bird, Wand2, Sun,
  Package, Box, Gem,
  Cherry, Citrus,
  Home, Store, Wheat, Trees, Landmark, Building2, Castle, Mountain, Church, Hammer,
  Pencil, Repeat, Feather, Moon, Compass, Flower2, Leaf, Anchor, Smile, Sunrise, AlertTriangle, CircleDashed, ArrowRight, Sword,
  Infinity: InfinityIcon,
  Coins, Banknote, Diamond, PiggyBank,
  Warehouse, Factory, Tent, TreePine, Tractor, GraduationCap,
  Skull, Drama, KeyRound, Telescope, Library, Ship,
  GaugeCircle, BookOpen, Atom, Layers,
  Cat, Dog, Rabbit, Fish,
  Hexagon, Triangle, ChevronsUp, Cloud, Wind, Snowflake,

  // Tabler Icons — mejor estilo para RPG/gaming
  IconSword, IconShield, IconSkull, IconFlame, IconSparkles, IconStar,
  IconTarget, IconTrophy, IconCrown, IconDiamond, IconGift, IconPackage,
  IconBox, IconLock, IconLockOpen, IconCalendar, IconBolt, IconTrendingUp,
  IconRocket, IconFlag, IconChecklist, IconHourglass, IconMap, IconBookmark,
  IconDice, IconCoins, IconMoon, IconSun,
  IconHeart, IconCrosshair, IconCompass, IconAnchor, IconFeather, IconLeaf,
  IconWind, IconCloud, IconSnowflake, IconHexagon,
  IconTriangle, IconAlertTriangle, IconArrowRight,
  IconPhone, IconMail, IconUsers, IconPencil, IconRepeat, IconSunrise,
  IconCashBanknote, IconPigMoney, IconTent, IconKey, IconTelescope, IconShip,
  IconGauge, IconBook, IconAtom, IconCat, IconDog, IconFish, IconEgg,
  IconTag, IconEye, IconSend, IconBuilding, IconHammer,
  IconChevronRight, IconCheck, IconChevronDown, IconChevronUp,
  IconHome, IconTree, IconMountain, IconMessageCircle, IconFileText, IconGlobe,
  IconWorld,
};

export const RAREZA_INFO: Record<Rareza, { label: string; ring: string; bg: string; text: string; glow: string; border: string }> = {
  comun: {
    label: 'Comun',
    ring: 'ring-slate-400/30',
    bg: 'from-slate-500/10 to-slate-400/5',
    text: 'text-slate-400',
    glow: 'shadow-slate-500/10',
    border: 'border-slate-400/20',
  },
  raro: {
    label: 'Raro',
    ring: 'ring-blue-400/40',
    bg: 'from-blue-500/15 to-cyan-500/5',
    text: 'text-blue-400',
    glow: 'shadow-blue-500/20',
    border: 'border-blue-400/30',
  },
  epico: {
    label: 'Epico',
    ring: 'ring-violet-400/50',
    bg: 'from-violet-500/20 to-fuchsia-500/10',
    text: 'text-violet-400',
    glow: 'shadow-violet-500/25',
    border: 'border-violet-400/40',
  },
  legendario: {
    label: 'Legendario',
    ring: 'ring-amber-400/60',
    bg: 'from-amber-500/25 to-orange-500/15',
    text: 'text-amber-400',
    glow: 'shadow-amber-500/30',
    border: 'border-amber-400/50',
  },
  mitico: {
    label: 'Mitico',
    ring: 'ring-rose-400/70',
    bg: 'from-rose-500/30 via-fuchsia-500/20 to-amber-500/10',
    text: 'text-rose-400',
    glow: 'shadow-rose-500/40',
    border: 'border-rose-400/60',
  },
};

export const CATEGORIA_INFO: Record<Categoria, { label: string; icon: IconType; color: string; accent: string }> = {
  comunicacion: { label: 'Comunicacion', icon: MessageCircle, color: 'text-emerald-500', accent: 'from-emerald-500/20 to-emerald-500/0' },
  cazador: { label: 'Cazador', icon: Target, color: 'text-blue-500', accent: 'from-blue-500/20 to-blue-500/0' },
  ventas: { label: 'Ventas', icon: TrendingUp, color: 'text-amber-500', accent: 'from-amber-500/20 to-amber-500/0' },
  marketing: { label: 'Marketing', icon: Rocket, color: 'text-fuchsia-500', accent: 'from-fuchsia-500/20 to-fuchsia-500/0' },
  productividad: { label: 'Productividad', icon: Activity, color: 'text-cyan-500', accent: 'from-cyan-500/20 to-cyan-500/0' },
};
